import type { Metadata } from "next";
import "./globals.css";
import { dmSans, roxter, streach, syne } from "@/utils/fonts";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { motion } from "framer-motion";
import LiquidGlass from "@/elements/LiquidGlass";
import Button from "@/elements/Button";
import { Plane } from "lucide-react";
import CTAButton from "@/components/CTAButton";
import SmoothScroll from "@/components/SmoothScroll";

export const metadata: Metadata = {
  title: "SkyBlue - Avation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.className} ${streach.variable} ${roxter.variable} ${syne.variable} antialiased relative`}
      >
        <SmoothScroll>
          <CTAButton />
          {children}
        </SmoothScroll>
      </body>
    </html>
  );
}
